### ISSUE TITLE
Error: Failed to parse blob

### ISSUE THREAD

**Issue by DhritiKhanna** [HansKristian-Work/dxil-spirv#102]
Hello HansKristian,

I am getting the following error when I keep my dxil files in a folder shaders/dk:
`[ERROR]: Failed to parse blob.`
`Error: Command '['build/dxil-spirv', '--output', '/tmp/tmpw8s9hededilan_gt1.qcc!eva_player_exe-Context-fb417d660ba93b43-Compile-170.PS.dc0d44c1.dxil', 'shaders/dk/dilan_gt1.qcc!eva_player_exe-Context-fb417d660ba93b43-Compile-170.PS.dc0d44c1.dxil', '--vertex-input', 'ATTR', '0', '--asm', '--glsl', '--validate', '--ssbo-uav', '--ssbo-srv']' returned non-zero exit status 1`

I am using Ubuntu 16.04, g++ version 7.5.0.

**Comment by HansKristian-Work** [comment]
That does not help me debug this issue at all.

**Comment by HansKristian-Work** [comment]
Closing due to no reply.
