### ISSUE TITLE
What would the difficulty be to go in the opposite direction?

### ISSUE THREAD

**Issue by reduz** [HansKristian-Work/dxil-spirv#103]
For some cases, it could be interesting to go in the opposite direction (SPIR-V to DXIL), what would you believe would be the level of difficulty in implementing this?

**Comment by reduz** [comment]
Yes, but for performance (and amount of failure points) reasons a more direct approach may be preferred.

**Comment by doitsujin** [comment]
> DXIL to SPIR-V

This is exactly what this project does.

**Comment by reduz** [comment]
@doitsujin my mistake, meant the opposite way.

**Comment by nanokatze** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/tree/main/src/microsoft/spirv_to_dxil

**Comment by reduz** [comment]
@nanokatze I think I have seen this in the past, but it relies for the most part on the Mesa IL right? Its a huge amount of code. Maybe it could be extracted?

**Comment by HansKristian-Work** [comment]
Emitting LLVM is a bit of a shitshow, but that's the main issue with emitting DXIL, although it is completely out of scope of this project.

**Comment by reduz** [comment]
@HansKristian-Work 

I see, its kind of a shame that no simple way to do this conversion exists. SPIRV-Cross has it out of scope, as well as this project. MESA has a converter but its entirely dependent on lots of MESA files.

This makes it very difficult to work on multi platform code that uses SPIR-V universally, as it is not possible to easily/efficiently convert to DXIL.

**Comment by HansKristian-Work** [comment]
Do you also support DX11? You'll probably have the same problem with DXBC there.

**Comment by reduz** [comment]
No, no interest from our part in suporting DX11, only Vulkan level APIs.

**Comment by iwubcode** [comment]
@reduz - curious what you ended up doing?  Currently we use glsang to take GLSL to SPIRV and then SPIRV-Cross to go to HLSL...then go to DXIL (DX12 backend) and DXBC (DX11 backend).  It works but it's in realtime and is quite slow.

**Comment by reduz** [comment]
@iwubcode We extracted the relevant bits from the MESA repository and now go via NIR. Probably still not ideal,but it works *a lot* better than SPIRV Cross -> HLSL -> DXIL.

Still hoping this project or another would write a dedicated converter at some point, as I think it should probably be easier to go SPIRV->DXIL, given how complex DXIL is in comparison.

https://github.com/godotengine/godot/pull/70315
