### ISSUE TITLE
parseIR doesn't read all bits

### ISSUE THREAD

**Issue by WistfulHopes** [HansKristian-Work/dxil-spirv#118]
The DXIL shader I am testing fails at parseIR with the AtEndOfStream check with 12 bytes left. I have attached the DXIL file below.

![image](https://user-images.githubusercontent.com/9942055/178796686-426c00f3-ce5d-480a-98fc-9a40a36ed466.png)
![image](https://user-images.githubusercontent.com/9942055/178797362-2202f0f9-25cd-415f-b717-9dd9ec2d9d8f.png)

[shader.zip](https://github.com/HansKristian-Work/dxil-spirv/files/9104569/shader.zip)

**Comment by HansKristian-Work** [comment]
This DXIL module is invalid I think. The native LLVM BC parser complains in `llvm::getBitcodeFileContents(MemoryBufferRef Buffer)` and returns "Malformed block" error.
