### ISSUE TITLE
Can the glsl code output keep the constant buffer variable names?

### ISSUE THREAD

**Issue by xoyojank** [HansKristian-Work/dxil-spirv#120]
we can get the variable names and register binding, but the glsl outputs do not contain them

**Comment by HansKristian-Work** [comment]
GLSL? Note that GLSL output only exists for the purpose of aiding the test suite.

**Comment by tomrus88** [comment]
> GLSL? Note that GLSL output only exists for the purpose of aiding the test suite.

We use glsl output for different purpose and it would be nice to have variable names of constant buffer structure preserved.

**Comment by HansKristian-Work** [comment]
Names inside the structure are not possible to preserve. DXIL does not work like that. `--use-reflection-names` can help emitting variable names on the OpVariable, but it requires the module to be built with reflection information.
