### ISSUE TITLE
Renaming spirv-headers

### ISSUE THREAD

**Issue by es20490446e** [HansKristian-Work/dxil-spirv#155]
Maybe renaming "spirv-headers" into "SPIRV-Headers" for consistency.

It helps a bit when packaging, as you can activate all modules in a loop:

    for Module in "${Modules[@]}"; do
        so git submodule init "${Dir}/${Module}"
        so git submodule set-url "${Dir}/${Module}" "${srcdir}/${Module#*/}"
        so git -c protocol.file.allow=always submodule update "${Dir}/${Module}"
    done

**Comment by HansKristian-Work** [comment]
Can't Modules just use the proper name? I don't understand why this helps.

**Comment by es20490446e** [comment]
I mean the name in this repository and on its own are different.

Hence when I clone the repos for building a package, those two names don't match. I have to manually specify this.

**Comment by HansKristian-Work** [comment]
Which packaging system is this for?

**Comment by es20490446e** [comment]
pacman:
https://gitlab.com/es20490446e/express-repository/-/blob/master/recipes/vkd3d-proton/PKGBUILD

**Comment by es20490446e** [comment]
Oki.
