### ISSUE TITLE
3DMark Sampler feedback feature test fails to run with "Unimplemented DXIL opcode 177"..

### ISSUE THREAD

**Issue by oscarbg** [HansKristian-Work/dxil-spirv#157]
Hi,
will try to capture dxil shaders later but for now fails..
log with:
07:49:37.279  INFO workload: 990c:err:vkd3d_dxil_log_callback: dxil-spirv: Unimplemented DXIL opcode 177
07:49:37.279  INFO workload: 990c:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to emit instruction.
07:49:37.279  INFO workload: 990c:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to convert function.
07:49:37.279  INFO workload: 990c:err:vkd3d_dxil_log_callback: dxil-spirv: Unimplemented DXIL opcode 177
07:49:37.279  INFO workload: 990c:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to emit instruction.
07:49:37.279  INFO workload: 990c:err:vkd3d_dxil_log_callback: dxil-spirv: Failed to convert function.

EDIT: using latest master & VKD3D_FEATURE_LEVEL=12_2 on a RTX 4070

**Comment by mbriar** [comment]
Pretty sure there is no equivalent vulkan feature to sampler feedback currently.

**Comment by mbriar** [comment]
I don't know about NV extensions or what Khronos is planning, but I suspect this will also only get any priority once actual games start depending on it.

**Comment by oscarbg** [comment]
Seems vk nv shader_texture_footprint ext should support exposing up to tier 0.9?

**Comment by HansKristian-Work** [comment]
It does not. It does not support the required filter modes.

**Comment by oscarbg** [comment]
thanks for explaining and sad to hear that extension still not enough.. and as you said it's last FL12.2 or DX Ultimate feature..
