### ISSUE TITLE
gpuopen TressFX sample assertion

### ISSUE THREAD

**Issue by mbriar** [HansKristian-Work/dxil-spirv#158]
6cd20427d70bda04.dxil from https://gpuopen.com/learn/sample-tressfx/ hits this assert:
```
dxil-spirv/node.cpp:290: static dxil_spv::CFGNode* dxil_spv::CFGNode::find_common_post_dominator(dxil_spv::CFGNode*, dxil_spv::CFGNode*): Assertion `a->immediate_post_dominator' failed.
```

shaders: 
[tressfx-shaders.zip](https://github.com/HansKristian-Work/dxil-spirv/files/11331596/tressfx-shaders.zip)

**Comment by HansKristian-Work** [comment]
vkd3d-proton stronk
