### ISSUE TITLE
Assertion failed: frontier

### ISSUE THREAD

**Issue by FilterUnfiltered** [HansKristian-Work/dxil-spirv#162]
Trying to get Greed of Man beta to work with proton, but it crashes when joining a lobby with the following error:
```
25155.030:019c:01ac:trace:seh:raise (22)
Assertion failed: frontier, file ../src-vkd3d-proton/subprojects/dxil-spirv/cfg_structurizer.cpp, line 1290
```

**Comment by mbriar** [comment]
Probably helpful if you dump and upload the *.dxil shaders using `VKD3D_SHADER_DUMP_PATH=/some/path`.

**Comment by FilterUnfiltered** [comment]
> Probably helpful if you dump and upload the *.dxil shaders using `VKD3D_SHADER_DUMP_PATH=/some/path`.

Which ones do you want, there are like 200

**Comment by mbriar** [comment]
Just zip them all up and post them here, should be small enough when compressed.

**Comment by FilterUnfiltered** [comment]
[shaders.zip](https://github.com/HansKristian-Work/dxil-spirv/files/11585518/shaders.zip)

**Comment by HansKristian-Work** [comment]
Fixed on master.
