### ISSUE TITLE
Failed to parse 

### ISSUE THREAD

**Issue by 648326374** [HansKristian-Work/dxil-spirv#193]
![fail](https://github.com/user-attachments/assets/0ea86226-03bc-4ad0-8c17-1f0a667b286b)

**Comment by K0bin** [comment]
Maybe attach the shaders that it fails to parse.

**Comment by 648326374** [comment]
The shader in the company can't be exported.The shader is transferred from dxbc.

**Comment by 648326374** [comment]
[2.cso.txt](https://github.com/user-attachments/files/16620099/2.cso.txt)
I've reproduced it. This is dxil converted from dxbc

**Comment by 648326374** [comment]
![image](https://github.com/user-attachments/assets/c0b5d928-e6ef-419f-b8f2-0ca366eaf4aa)
use dxc can parse it.
dxc.exe -dumpbin C:\Users\Administrator\Desktop\2.cso.txt

**Comment by 648326374** [comment]
I have fixed this bug, can I submit the code

**Comment by HansKristian-Work** [comment]
Fix is on master.
