### ISSUE TITLE
Unimplemented DXIL opcode 41

### ISSUE THREAD

**Issue by 648326374** [HansKristian-Work/dxil-spirv#197]
ok.\shader104.cso
[ERROR]: Unimplemented DXIL opcode 41
[ERROR]: Failed to emit instruction.
[ERROR]: Failed to convert function.
[ERROR]: Failed to convert DXIL to SPIR-V.
[Uploading err.zip…]()

**Comment by HansKristian-Work** [comment]
Fixed on master.
