### ISSUE TITLE
Unknown type

### ISSUE THREAD

**Issue by 648326374** [HansKristian-Work/dxil-spirv#198]
.\shader155.cso
[ERROR]: Unknown type!
[ERROR]: Failed to parse blob.
[err.zip](https://github.com/user-attachments/files/16667627/err.zip)

**Comment by 648326374** [comment]
![image](https://github.com/user-attachments/assets/1693482c-8e13-440d-96e7-4388ce5cbd3e)
I exported the shader in autocad, a total of 227. There are now 41 shader errors,There are two categories in total, both of which are listed in issue.

**Comment by HansKristian-Work** [comment]
All the shaders in the archive are now passing on master.

**Comment by 648326374** [comment]
thank you
