### ISSUE TITLE
Star Wars Outlaws RT option crash

### ISSUE THREAD

**Issue by Blisto91** [HansKristian-Work/dxil-spirv#199]
#### Edit: see second comment below (https://github.com/HansKristian-Work/dxil-spirv/issues/199#issuecomment-2321718287) for newest update

Port of  https://gitlab.freedesktop.org/mesa/mesa/-/issues/11792 as @KonstantinSeurer says it is a likely dxil-spirv issue.

When setting "Raytraced contact shadows" to medium or high in Star Wars Outlaws the game will crash to desktop.

Lines of interest from Proton log
```
SPIR-V parsing FAILED:
    In file ../src/compiler/spirv/vtn_structured_cfg.c:759
    count_construct_stack(&stack) == 1
    57800 bytes into the SPIR-V binary
```
spirv-val output from fossilize dump
```
Fossilize ERROR: spirv-val: Block '2277[%2277]' is already a merge block for another header
  %main = OpFunction %void None %3

Fossilize WARN: Failed to validate SPIR-V module: 77A1CA823A69C837, skipping!
Fossilize ERROR: spirv-val: Header block '2214[%2214]' is contained in the loop construct headed by '2187[%2187]', but its merge block '2269[%2269]' is not
  %2214 = OpLabel

Fossilize WARN: Failed to validate SPIR-V module: 375CAED7A0FC8DFD, skipping!
Fossilize ERROR: spirv-val: [VUID-StandaloneSpirv-Base-04781] Expected 32-bit int type for Base operand: BitCount
  %693 = OpBitCount %uint %692

Fossilize WARN: Failed to validate SPIR-V module: 610BDB6326633B92, skipping!
```

#### System information

- GPU: 7900 xtx
- Driver: radv 23.2.1 to master (below doesn't start)
- vkd3d-proton: 2.12 - master (below doesn't start)

#### Steps to reproduce

1. Start game (only to main menu is fine)
2. Enter SETTINGS -> Graphics -> Advanced graphics
3. Change "Raytraced contact shadows" to medium or high and hit apply
4. Observe crash

#### API captures

[fossizile-dump.tar.gz](/uploads/0d621fc5478314d570fdbc1c0c0c127f/fossizile-dump.tar.gz)

#### Log

[outlaws-rt-crash-debug.tar.gz](/uploads/1839cfbc287e86290f17f6d8be7bcb56/outlaws-rt-crash-debug.tar.gz)

**Comment by Blisto91** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/pull/2096 have fixed the spir-v validation errors.
Mesa issue have been reopened as rad still crashes

**Comment by Blisto91** [comment]
@KonstantinSeurer Managed to dump the crashing spirv that fails validation. Not sure why fossilize wasn't showing anything.
[fail-0.spirv.tar.gz](https://github.com/user-attachments/files/16819346/fail-0.spirv.tar.gz)

**Comment by Blisto91** [comment]
Shader dump made with `VKD3D_SHADER_DUMP_PATH`
https://drive.proton.me/urls/51R8YWGFBW#pye8rJrHT96a

**Comment by Saancreed** [comment]
Another dump, this time made from about half an hour of gameplay with every setting cranked up to max on Nvidia: https://drive.google.com/file/d/1_D7fxoZe9u1A0kUbRPHY-GUxbnER0JiA/view?usp=drivesdk

**Comment by Blisto91** [comment]
Fixed https://github.com/HansKristian-Work/vkd3d-proton/pull/2110
