### ISSUE TITLE
Red Dead Redemption 2 d3d12 spirv-val error

### ISSUE THREAD

**Issue by Blisto91** [HansKristian-Work/dxil-spirv#201]
[Red Dead Redemption 2](https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/) crashes in radv when running d3d12 mode with
```
SPIR-V parsing FAILED:
    In file ../src/compiler/spirv/vtn_cfg.c:393
    b->block && b->block->branch == NULL
    5344 bytes into the SPIR-V binary
```

A spirv-val from a Fossilize dump shows
```
Fossilize ERROR: spirv-val: Return must appear in a block
  OpReturn

Fossilize WARN: Failed to validate SPIR-V module: 77535ADFFD072E7A, skipping!

```

Archive with dumps both via `VKD3D_SHADER_DUMP_PATH` and Fossilize
https://drive.proton.me/urls/5CMJFEVKTW#2dEQZT81WRcJ

**Comment by mbriar** [comment]
Looks like it's using dxbc exclusively (expected since it's an old game)? So probably should be reported over at the vkd3d-proton github.

**Comment by Blisto91** [comment]
Yes you are right. Didn't even consider to look if it didn't use dxil. Moved in to the existing vkd3d-proton issue https://github.com/HansKristian-Work/vkd3d-proton/issues/1623#issuecomment-2329654192
