### ISSUE TITLE
dxil convert to spirv fail

### ISSUE THREAD

**Issue by Mario-Cui** [HansKristian-Work/dxil-spirv#203]
this dxil is generate from Microsoft dxbc2dxil tool, but convert to spirv the following error occurred,
![image](https://github.com/user-attachments/assets/587adb33-032b-440b-82db-23bcb4441f0a)
[cs5_1.zip](https://github.com/user-attachments/files/17042018/cs5_1.zip)

**Comment by HansKristian-Work** [comment]
This is technically broken DXIL. It says the UAV doesn't have a counter, but it tries to use one anyway.

**Comment by HansKristian-Work** [comment]
Worked around it.
