### ISSUE TITLE
Assertion failed in CFGNode::retarget_branch

### ISSUE THREAD

**Issue by davidjmemmett** [HansKristian-Work/dxil-spirv#78]
Hi,

I'm unsure if this belongs here or in `vkd3d-proton`.

Reproducible with latest `vkd3d-proton` & `dxil-spirv` on F1 2021.

```
20568.822:010c:01ac:trace:seh:raise (22)
Assertion failed: std::find(succ.begin(), succ.end(), to_next) == succ.end(), file ../src-vkd3d-proton/subprojects/dxil-spirv/node.cpp, line 354
```

[steam-1134570.log](https://github.com/ValveSoftware/Proton/files/6910481/steam-1134570.log)

_Originally posted in Proton issue: https://github.com/ValveSoftware/Proton/issues/4966#issuecomment-890273324_

Cheers,
David

**Comment by dave-juicelabs** [comment]
I can also reproduce this with the attached.
[cs_post_opaque_processes_prepass.zip](https://github.com/HansKristian-Work/dxil-spirv/files/6941048/cs_post_opaque_processes_prepass.zip)

**Comment by HansKristian-Work** [comment]
Back from holiday now, I'll have a look.

**Comment by HansKristian-Work** [comment]
Reproduced the assert.
