### ISSUE TITLE
Not compiling on GCC 6.3

### ISSUE THREAD

**Issue by jrugia** [HansKristian-Work/dxil-spirv#8]
In reference to earlier today's ticket at: https://github.com/HansKristian-Work/vkd3d-proton/issues/212 

I've tried to build dxil-spirv by itself without vkd3d but the compile still fails.

Steps I took:

1) extracted dxil-spirv itself.
2) extracted 'spirv-headers', 'spirv-cross' and 'spirv-tools' in their respective 'third_party' folder.
3) ran: 'meson . ./build' (folder I used for compilation)
4) 'cd build' and then 'ninja'

![1](https://user-images.githubusercontent.com/13750621/87826980-29bc6800-c87a-11ea-83a1-078330314b4c.png)

![2](https://user-images.githubusercontent.com/13750621/87826988-2de88580-c87a-11ea-9031-c631e6f19cbd.png)

Let me know if there's anything else I could try.

**Comment by HansKristian-Work** [comment]
Should be fixed now.
